openapi: 3.0.0
info:
  version: 1.0.0
  title: GameBoard Webshop
  description: Endpoint Documentation
servers:
  - url: http://localhost:3000
paths:
  /products:
    get:
      description: Return a list of products
      responses:
        '200':
          description: List of products returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  # /products:
  #   get:
  #     description: Return a list of products
  #     responses:
  #       '200':
  #         description: List of products returned successfully
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Product'
  /products/{_id}:
    get:
      description: Get a product
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Returns a Product
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Product'
    patch:
      description: Updates a product
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product has been updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /products/search/{cat}:
    get:
      description: Search a product by Category
      parameters:
        - in: path
          name: cat
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Returns a Product
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Product'
  /login:
    post:
      description: Create a new products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Product has been created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orders:
    get:
      description: Return a ordered of products
      responses:
        '200':
          description: List of  ordered products returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      description: Creates a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Product has been created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
  /orders/{_id}:
    get:
      description: Order a product
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Returns a Ordered Product
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Order'
    patch:
      description: Updates a product
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Product has been updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /addresses:
    get:
      description: Return an address
      responses:
        '200':
          description: Return an address successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Address'
    post:
      description: Creates a new address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Address has been created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /addresses/{_id}:
    get:
      description: Return an address
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Returns an Address
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Address'
    patch:
      description: Updates an address
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Address has been updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - description
        - datasheet
        - image
        - price
      properties:
        name:
          type: string
        description:
          type: string
        datasheet:
          type: string
        image:
          type: string
        price:
          type: number
    Error:
      type: object
      required:
        - message
        - has_error
      properties:
        message:
          type: string
        has_error:
          type: boolean
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - message
        - has_error
      properties:
        message:
          type: string
        has_error:
          type: boolean
    Order:
      type: object
      required:
        - address
        - product
      properties:
        address:
          type: object
        product:
          type: object
    Error:
      type: object
      required:
        - message
        - has_error
      properties:
        message:
          type: string
        has_error:
          type: boolean
    Address:
      type: object
      required:
        - country
        - city
        - street
        - notes
      properties:
        country:
          type: string
        city:
          type: string
        street:
          type: string
        notes:
          type: string
    Error:
      type: object
      required:
        - message
        - has_error
      properties:
        message:
          type: string
        has_error:
          type: boolean
  